# docker-compose up -d && docker exec -it maresias_atlantico bash
version: "3"

services:
  node:
    image: node:16.14
    container_name: maresias_atlantico
    build: ./ 
    tty: true
    stdin_open: true
    command: bash
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - mongodb
    ports:
      - 3002:3002
    environment:
      - MONGO_URI=mongodb://mongodb:27017/CarShop

  mongodb:
    image: mongo:5.0.7
    container_name: maresias_atlantico_db
    volumes:
      - ./:/app
    restart: always
    ports:
      - 27018:27017

networks:
  default:
    name: maresias_atlantico_net

